services:

  web:
    build: ../web
    container_name: dev-web
    restart: always
    ports:
      - "3002:3000"
    networks:
      - dev-network

  admin:
    build: ../admin
    container_name: dev-admin
    restart: always
    ports:
      - "8083:80"
    networks:
      - dev-network

  backend:
    build: ../backend
    container_name: dev-backend
    restart: always
    ports:
      - "5002:5000"
    networks:
      - dev-network

  strapi:
    build: ../strapi
    container_name: dev-strapi
    restart: always
    ports:
      - "1339:1337"
    env_file:
      - ../strapi/.env
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
